version: '3.1'

services:

  wordpress:
    container_name: docker_wordpress_1
    image: wordpress:php5.6-apache
    restart: always
    ports:
      - 80:80
    links:
      - mysql
    volumes:
      - ../app1:/var/www/html
      - ./docker:/tmp

  mysql:
    container_name: docker_mysql_1
    image: mysql:5.6.38
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/tmp/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test